<?php
/**
 * CreatePaymentResult
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * GOV.UK Pay API
 *
 * The GOV.UK Pay REST API. Read [our documentation](https://docs.payments.service.gov.uk/) for more details.
 *
 * OpenAPI spec version: 1.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.68
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * CreatePaymentResult Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CreatePaymentResult implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'CreatePaymentResult';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        '_links' => '\Swagger\Client\Model\PaymentLinks',
        'amount' => 'int',
        'card_details' => '\Swagger\Client\Model\CardDetailsFromResponse',
        'created_date' => 'string',
        'delayed_capture' => 'bool',
        'description' => 'string',
        'email' => 'string',
        'language' => 'string',
        'metadata' => '\Swagger\Client\Model\ExternalMetadata',
        'moto' => 'bool',
        'payment_id' => 'string',
        'payment_provider' => 'string',
        'provider_id' => 'string',
        'reference' => 'string',
        'refund_summary' => '\Swagger\Client\Model\RefundSummary',
        'return_url' => 'string',
        'settlement_summary' => '\Swagger\Client\Model\PaymentSettlementSummary',
        'state' => '\Swagger\Client\Model\PaymentState'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        '_links' => null,
        'amount' => 'int64',
        'card_details' => null,
        'created_date' => null,
        'delayed_capture' => null,
        'description' => null,
        'email' => null,
        'language' => null,
        'metadata' => null,
        'moto' => null,
        'payment_id' => null,
        'payment_provider' => null,
        'provider_id' => null,
        'reference' => null,
        'refund_summary' => null,
        'return_url' => null,
        'settlement_summary' => null,
        'state' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        '_links' => '_links',
        'amount' => 'amount',
        'card_details' => 'card_details',
        'created_date' => 'created_date',
        'delayed_capture' => 'delayed_capture',
        'description' => 'description',
        'email' => 'email',
        'language' => 'language',
        'metadata' => 'metadata',
        'moto' => 'moto',
        'payment_id' => 'payment_id',
        'payment_provider' => 'payment_provider',
        'provider_id' => 'provider_id',
        'reference' => 'reference',
        'refund_summary' => 'refund_summary',
        'return_url' => 'return_url',
        'settlement_summary' => 'settlement_summary',
        'state' => 'state'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        '_links' => 'setLinks',
        'amount' => 'setAmount',
        'card_details' => 'setCardDetails',
        'created_date' => 'setCreatedDate',
        'delayed_capture' => 'setDelayedCapture',
        'description' => 'setDescription',
        'email' => 'setEmail',
        'language' => 'setLanguage',
        'metadata' => 'setMetadata',
        'moto' => 'setMoto',
        'payment_id' => 'setPaymentId',
        'payment_provider' => 'setPaymentProvider',
        'provider_id' => 'setProviderId',
        'reference' => 'setReference',
        'refund_summary' => 'setRefundSummary',
        'return_url' => 'setReturnUrl',
        'settlement_summary' => 'setSettlementSummary',
        'state' => 'setState'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        '_links' => 'getLinks',
        'amount' => 'getAmount',
        'card_details' => 'getCardDetails',
        'created_date' => 'getCreatedDate',
        'delayed_capture' => 'getDelayedCapture',
        'description' => 'getDescription',
        'email' => 'getEmail',
        'language' => 'getLanguage',
        'metadata' => 'getMetadata',
        'moto' => 'getMoto',
        'payment_id' => 'getPaymentId',
        'payment_provider' => 'getPaymentProvider',
        'provider_id' => 'getProviderId',
        'reference' => 'getReference',
        'refund_summary' => 'getRefundSummary',
        'return_url' => 'getReturnUrl',
        'settlement_summary' => 'getSettlementSummary',
        'state' => 'getState'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const LANGUAGE_EN = 'en';
    const LANGUAGE_CY = 'cy';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getLanguageAllowableValues()
    {
        return [
            self::LANGUAGE_EN,
            self::LANGUAGE_CY,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['_links'] = isset($data['_links']) ? $data['_links'] : null;
        $this->container['amount'] = isset($data['amount']) ? $data['amount'] : null;
        $this->container['card_details'] = isset($data['card_details']) ? $data['card_details'] : null;
        $this->container['created_date'] = isset($data['created_date']) ? $data['created_date'] : null;
        $this->container['delayed_capture'] = isset($data['delayed_capture']) ? $data['delayed_capture'] : null;
        $this->container['description'] = isset($data['description']) ? $data['description'] : null;
        $this->container['email'] = isset($data['email']) ? $data['email'] : null;
        $this->container['language'] = isset($data['language']) ? $data['language'] : null;
        $this->container['metadata'] = isset($data['metadata']) ? $data['metadata'] : null;
        $this->container['moto'] = isset($data['moto']) ? $data['moto'] : null;
        $this->container['payment_id'] = isset($data['payment_id']) ? $data['payment_id'] : null;
        $this->container['payment_provider'] = isset($data['payment_provider']) ? $data['payment_provider'] : null;
        $this->container['provider_id'] = isset($data['provider_id']) ? $data['provider_id'] : null;
        $this->container['reference'] = isset($data['reference']) ? $data['reference'] : null;
        $this->container['refund_summary'] = isset($data['refund_summary']) ? $data['refund_summary'] : null;
        $this->container['return_url'] = isset($data['return_url']) ? $data['return_url'] : null;
        $this->container['settlement_summary'] = isset($data['settlement_summary']) ? $data['settlement_summary'] : null;
        $this->container['state'] = isset($data['state']) ? $data['state'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getLanguageAllowableValues();
        if (!is_null($this->container['language']) && !in_array($this->container['language'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'language', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets _links
     *
     * @return \Swagger\Client\Model\PaymentLinks
     */
    public function getLinks()
    {
        return $this->container['_links'];
    }

    /**
     * Sets _links
     *
     * @param \Swagger\Client\Model\PaymentLinks $_links _links
     *
     * @return $this
     */
    public function setLinks($_links)
    {
        $this->container['_links'] = $_links;

        return $this;
    }

    /**
     * Gets amount
     *
     * @return int
     */
    public function getAmount()
    {
        return $this->container['amount'];
    }

    /**
     * Sets amount
     *
     * @param int $amount The amount, in pence, the user has paid or will pay. `amount` will match the value you sent in the request body.
     *
     * @return $this
     */
    public function setAmount($amount)
    {
        $this->container['amount'] = $amount;

        return $this;
    }

    /**
     * Gets card_details
     *
     * @return \Swagger\Client\Model\CardDetailsFromResponse
     */
    public function getCardDetails()
    {
        return $this->container['card_details'];
    }

    /**
     * Sets card_details
     *
     * @param \Swagger\Client\Model\CardDetailsFromResponse $card_details card_details
     *
     * @return $this
     */
    public function setCardDetails($card_details)
    {
        $this->container['card_details'] = $card_details;

        return $this;
    }

    /**
     * Gets created_date
     *
     * @return string
     */
    public function getCreatedDate()
    {
        return $this->container['created_date'];
    }

    /**
     * Sets created_date
     *
     * @param string $created_date The date you created the payment.
     *
     * @return $this
     */
    public function setCreatedDate($created_date)
    {
        $this->container['created_date'] = $created_date;

        return $this;
    }

    /**
     * Gets delayed_capture
     *
     * @return bool
     */
    public function getDelayedCapture()
    {
        return $this->container['delayed_capture'];
    }

    /**
     * Sets delayed_capture
     *
     * @param bool $delayed_capture `delayed_capture` is `true` if you’re controlling [when GOV.UK Pay takes (‘captures’) the payment from the paying user’s bank account](https://docs.payments.service.gov.uk/delayed_capture).
     *
     * @return $this
     */
    public function setDelayedCapture($delayed_capture)
    {
        $this->container['delayed_capture'] = $delayed_capture;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string $description The description you sent in the request body when creating this payment.
     *
     * @return $this
     */
    public function setDescription($description)
    {
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets email
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param string $email The paying user’s email address. The paying user’s email field will be prefilled with this value when they make their payment. `email` does not appear if you did not include it in the request body.
     *
     * @return $this
     */
    public function setEmail($email)
    {
        $this->container['email'] = $email;

        return $this;
    }

    /**
     * Gets language
     *
     * @return string
     */
    public function getLanguage()
    {
        return $this->container['language'];
    }

    /**
     * Sets language
     *
     * @param string $language The language of the user’s payment page.
     *
     * @return $this
     */
    public function setLanguage($language)
    {
        $allowedValues = $this->getLanguageAllowableValues();
        if (!is_null($language) && !in_array($language, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'language', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['language'] = $language;

        return $this;
    }

    /**
     * Gets metadata
     *
     * @return \Swagger\Client\Model\ExternalMetadata
     */
    public function getMetadata()
    {
        return $this->container['metadata'];
    }

    /**
     * Sets metadata
     *
     * @param \Swagger\Client\Model\ExternalMetadata $metadata metadata
     *
     * @return $this
     */
    public function setMetadata($metadata)
    {
        $this->container['metadata'] = $metadata;

        return $this;
    }

    /**
     * Gets moto
     *
     * @return bool
     */
    public function getMoto()
    {
        return $this->container['moto'];
    }

    /**
     * Sets moto
     *
     * @param bool $moto Indicates if this payment is a [Mail Order / Telephone Order (MOTO) payment](https://docs.payments.service.gov.uk/moto_payments).
     *
     * @return $this
     */
    public function setMoto($moto)
    {
        $this->container['moto'] = $moto;

        return $this;
    }

    /**
     * Gets payment_id
     *
     * @return string
     */
    public function getPaymentId()
    {
        return $this->container['payment_id'];
    }

    /**
     * Sets payment_id
     *
     * @param string $payment_id The unique ID GOV.UK Pay automatically associated with this payment when you created it.
     *
     * @return $this
     */
    public function setPaymentId($payment_id)
    {
        $this->container['payment_id'] = $payment_id;

        return $this;
    }

    /**
     * Gets payment_provider
     *
     * @return string
     */
    public function getPaymentProvider()
    {
        return $this->container['payment_provider'];
    }

    /**
     * Sets payment_provider
     *
     * @param string $payment_provider payment_provider
     *
     * @return $this
     */
    public function setPaymentProvider($payment_provider)
    {
        $this->container['payment_provider'] = $payment_provider;

        return $this;
    }

    /**
     * Gets provider_id
     *
     * @return string
     */
    public function getProviderId()
    {
        return $this->container['provider_id'];
    }

    /**
     * Sets provider_id
     *
     * @param string $provider_id The reference number your payment service provider associated with the payment.
     *
     * @return $this
     */
    public function setProviderId($provider_id)
    {
        $this->container['provider_id'] = $provider_id;

        return $this;
    }

    /**
     * Gets reference
     *
     * @return string
     */
    public function getReference()
    {
        return $this->container['reference'];
    }

    /**
     * Sets reference
     *
     * @param string $reference The reference number you associated with this payment.
     *
     * @return $this
     */
    public function setReference($reference)
    {
        $this->container['reference'] = $reference;

        return $this;
    }

    /**
     * Gets refund_summary
     *
     * @return \Swagger\Client\Model\RefundSummary
     */
    public function getRefundSummary()
    {
        return $this->container['refund_summary'];
    }

    /**
     * Sets refund_summary
     *
     * @param \Swagger\Client\Model\RefundSummary $refund_summary refund_summary
     *
     * @return $this
     */
    public function setRefundSummary($refund_summary)
    {
        $this->container['refund_summary'] = $refund_summary;

        return $this;
    }

    /**
     * Gets return_url
     *
     * @return string
     */
    public function getReturnUrl()
    {
        return $this->container['return_url'];
    }

    /**
     * Sets return_url
     *
     * @param string $return_url The URL you direct the paying user to after their payment journey on GOV.UK Pay ends.
     *
     * @return $this
     */
    public function setReturnUrl($return_url)
    {
        $this->container['return_url'] = $return_url;

        return $this;
    }

    /**
     * Gets settlement_summary
     *
     * @return \Swagger\Client\Model\PaymentSettlementSummary
     */
    public function getSettlementSummary()
    {
        return $this->container['settlement_summary'];
    }

    /**
     * Sets settlement_summary
     *
     * @param \Swagger\Client\Model\PaymentSettlementSummary $settlement_summary settlement_summary
     *
     * @return $this
     */
    public function setSettlementSummary($settlement_summary)
    {
        $this->container['settlement_summary'] = $settlement_summary;

        return $this;
    }

    /**
     * Gets state
     *
     * @return \Swagger\Client\Model\PaymentState
     */
    public function getState()
    {
        return $this->container['state'];
    }

    /**
     * Sets state
     *
     * @param \Swagger\Client\Model\PaymentState $state state
     *
     * @return $this
     */
    public function setState($state)
    {
        $this->container['state'] = $state;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
