<?php
/**
 * AuthorisationRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * GOV.UK Pay API
 *
 * The GOV.UK Pay REST API. Read [our documentation](https://docs.payments.service.gov.uk/) for more details.
 *
 * OpenAPI spec version: 1.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.68
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * AuthorisationRequestTest Class Doc Comment
 *
 * @category    Class
 * @description Contains the user&#x27;s payment information. This information will be sent to the payment service provider to authorise the payment.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AuthorisationRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "AuthorisationRequest"
     */
    public function testAuthorisationRequest()
    {
    }

    /**
     * Test attribute "card_number"
     */
    public function testPropertyCardNumber()
    {
    }

    /**
     * Test attribute "cardholder_name"
     */
    public function testPropertyCardholderName()
    {
    }

    /**
     * Test attribute "cvc"
     */
    public function testPropertyCvc()
    {
    }

    /**
     * Test attribute "expiry_date"
     */
    public function testPropertyExpiryDate()
    {
    }

    /**
     * Test attribute "one_time_token"
     */
    public function testPropertyOneTimeToken()
    {
    }
}
