<?php
/**
 * PaymentDetailForSearchTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * GOV.UK Pay API
 *
 * The GOV.UK Pay REST API. Read [our documentation](https://docs.payments.service.gov.uk/) for more details.
 *
 * OpenAPI spec version: 1.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.68
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * PaymentDetailForSearchTest Class Doc Comment
 *
 * @category    Class
 * @description Contains payments matching your search criteria.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PaymentDetailForSearchTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PaymentDetailForSearch"
     */
    public function testPaymentDetailForSearch()
    {
    }

    /**
     * Test attribute "_links"
     */
    public function testPropertyLinks()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "authorisation_mode"
     */
    public function testPropertyAuthorisationMode()
    {
    }

    /**
     * Test attribute "authorisation_summary"
     */
    public function testPropertyAuthorisationSummary()
    {
    }

    /**
     * Test attribute "card_brand"
     */
    public function testPropertyCardBrand()
    {
    }

    /**
     * Test attribute "card_details"
     */
    public function testPropertyCardDetails()
    {
    }

    /**
     * Test attribute "corporate_card_surcharge"
     */
    public function testPropertyCorporateCardSurcharge()
    {
    }

    /**
     * Test attribute "created_date"
     */
    public function testPropertyCreatedDate()
    {
    }

    /**
     * Test attribute "delayed_capture"
     */
    public function testPropertyDelayedCapture()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "exemption"
     */
    public function testPropertyExemption()
    {
    }

    /**
     * Test attribute "fee"
     */
    public function testPropertyFee()
    {
    }

    /**
     * Test attribute "language"
     */
    public function testPropertyLanguage()
    {
    }

    /**
     * Test attribute "metadata"
     */
    public function testPropertyMetadata()
    {
    }

    /**
     * Test attribute "moto"
     */
    public function testPropertyMoto()
    {
    }

    /**
     * Test attribute "net_amount"
     */
    public function testPropertyNetAmount()
    {
    }

    /**
     * Test attribute "payment_id"
     */
    public function testPropertyPaymentId()
    {
    }

    /**
     * Test attribute "payment_provider"
     */
    public function testPropertyPaymentProvider()
    {
    }

    /**
     * Test attribute "provider_id"
     */
    public function testPropertyProviderId()
    {
    }

    /**
     * Test attribute "reference"
     */
    public function testPropertyReference()
    {
    }

    /**
     * Test attribute "refund_summary"
     */
    public function testPropertyRefundSummary()
    {
    }

    /**
     * Test attribute "return_url"
     */
    public function testPropertyReturnUrl()
    {
    }

    /**
     * Test attribute "settlement_summary"
     */
    public function testPropertySettlementSummary()
    {
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
    }

    /**
     * Test attribute "total_amount"
     */
    public function testPropertyTotalAmount()
    {
    }
}
