<?php
/**
 * CardPaymentsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * GOV.UK Pay API
 *
 * The GOV.UK Pay REST API. Read [our documentation](https://docs.payments.service.gov.uk/) for more details.
 *
 * OpenAPI spec version: 1.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.68
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * CardPaymentsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CardPaymentsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for cancelAPayment
     *
     * Cancel payment.
     *
     */
    public function testCancelAPayment()
    {
    }

    /**
     * Test case for captureAPayment
     *
     * Take a delayed payment.
     *
     */
    public function testCaptureAPayment()
    {
    }

    /**
     * Test case for createAPayment
     *
     * Create a payment.
     *
     */
    public function testCreateAPayment()
    {
    }

    /**
     * Test case for getAPayment
     *
     * Get information about a single payment.
     *
     */
    public function testGetAPayment()
    {
    }

    /**
     * Test case for getEventsForAPayment
     *
     * Get a payment's events.
     *
     */
    public function testGetEventsForAPayment()
    {
    }

    /**
     * Test case for searchPayments
     *
     * Search payments.
     *
     */
    public function testSearchPayments()
    {
    }
}
